url: "https://chooselikebuddha.com"
baseurl: ""

page_title: Choose Like Buddha
title: Choose Like Buddha
description: "Train your mind to respond, not react — with short daily choices inspired by mindfulness."

# App Info
ios_app_id: 6757470935
appstore_link: https://apps.apple.com/app/id6757470935
playstore_link: https://play.google.com/store/apps/details?id=com.tigransimonyan.chooselikebuddha&pcampaignid=web_share
app_icon: assets/logo.png
app_name: Choose Like Buddha
app_price: Free
app_description: "Train your mind to respond, not react — with short daily choices inspired by mindfulness."

enable_smart_app_banner: true

# Owner
your_name: Tigran
email_address: tigran.contractor@gmail.com

permalink: /blog/:title/

paginate: 20
paginate_path: "/blog/page-:num/"

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - Gemfile
  - Gemfile.lock
  - postcss.config.js
  - LICENSE
  - README.md
